#ifndef __AUX_H__
#define __AUX_H__

#include "base.h"

#define AUX_UART_CLOCK  500000000
#define AUX_MU_BAUD(baud) ((AUX_UART_CLOCK/(baud*8))-1)

#define AUX_BASE_PERIPHERAL     PERIPHERAL_BASE_ADDR + 0x215000U

#define AUX_IRQ_OFFSET          0x00U
#define AUX_IRQ_ADDR            (AUX_BASE_PERIPHERAL + AUX_IRQ_OFFSET)
#define AUX_ENABLES_OFFSET      0x04U
#define AUX_ENABLES_ADDR        (AUX_BASE_PERIPHERAL + AUX_ENABLES_OFFSET)
#define AUX_MU_IO_REG_OFFSET    0x40U
#define AUX_MU_IO_REG_ADDR      (AUX_BASE_PERIPHERAL + AUX_MU_IO_REG_OFFSET)
#define AUX_MU_IER_REG_OFFSET   0x44U
#define AUX_MU_IER_REG_ADDR     (AUX_BASE_PERIPHERAL + AUX_MU_IER_REG_OFFSET)
#define AUX_MU_IIR_REG_OFFSET   0x48U
#define AUX_MU_IIR_REG_ADDR     (AUX_BASE_PERIPHERAL + AUX_MU_IIR_REG_OFFSET)
#define AUX_MU_LCR_REG_OFFSET   0x4CU
#define AUX_MU_LCR_REG_ADDR     (AUX_BASE_PERIPHERAL + AUX_MU_LCR_REG_OFFSET)
#define AUX_MU_MCR_REG_OFFSET   0x50U
#define AUX_MU_MCR_REG_ADDR     (AUX_BASE_PERIPHERAL + AUX_MU_MCR_REG_OFFSET)
#define AUX_MU_LSR_REG_OFFSET   0x54U
#define AUX_MU_LSR_REG_ADDR     (AUX_BASE_PERIPHERAL + AUX_MU_LSR_REG_OFFSET)
#define AUX_MU_MSR_REG_OFFSET   0x58U
#define AUX_MU_MSR_REG_ADDR     (AUX_BASE_PERIPHERAL + AUX_MU_MSR_REG_OFFSET)
#define AUX_MU_SCRATCH_OFFSET   0x5CU
#define AUX_MU_SCRATCH_ADDR     (AUX_BASE_PERIPHERAL + AUX_MU_SCRATCH_OFFSET)
#define AUX_MU_CNTL_REG_OFFSET  0x60U
#define AUX_MU_CNTL_REG_ADDR    (AUX_BASE_PERIPHERAL + AUX_MU_CNTL_REG_OFFSET)
#define AUX_MU_STAT_REG_OFFSET  0x64U
#define AUX_MU_STAT_REG_ADDR    (AUX_BASE_PERIPHERAL + AUX_MU_STAT_REG_OFFSET)
#define AUX_MU_BAUD_REG_OFFSET  0x68U
#define AUX_MU_BAUD_REG_ADDR    (AUX_BASE_PERIPHERAL + AUX_MU_BAUD_REG_OFFSET)

/* TODO for SPI
0x80 AUX_SPI1_CNTL0_REG SPI 1 Control register 0
0x84 AUX_SPI1_CNTL1_REG SPI 1 Control register 1
0x88 AUX_SPI1_STAT_REG SPI 1 Status
0x8c AUX_SPI1_PEEK_REG SPI 1 Peek
0xa0 AUX_SPI1_IO_REGa SPI 1 Data
0xa4 AUX_SPI1_IO_REGb SPI 1 Data
0xa8 AUX_SPI1_IO_REGc SPI 1 Data
0xac AUX_SPI1_IO_REGd SPI 1 Data
0xb0 AUX_SPI1_TXHOLD_REGa SPI 1 Extended Data
0xb4 AUX_SPI1_TXHOLD_REGb SPI 1 Extended Data
0xb8 AUX_SPI1_TXHOLD_REGc SPI 1 Extended Data
0xbc AUX_SPI1_TXHOLD_REGd SPI 1 Extended Data
0xc0 AUX_SPI2_CNTL0_REG SPI 2 Control register 0
*/

#endif